### ISSUE TITLE
[Feature]: Add vessel temperature information

### ISSUE THREAD

**Issue by bespezzano** [LRTNZ/KerbalSimpitRevamped#51]
## Is your feature request related to a problem? Please describe.
<br> 

Add vessel temperature information

### What is the issue that you are facing, that you would like resolved? How would it benefit players?

<br>

Users could use this information to display overheating alarm and / or temp information.

## Describe the solution you'd like

<br>

Expose temperature information like another resource. Seeing each part has a Core and Skin temp, this will probably have to be presented as an overall percentage of the max temp before overheating if that makes sense

**Comment by TheDicko** [comment]
I guess the main issue is that each part has its own values rather than the ship as a whole. I cant see away of sending all the parts temperature readings without making the plugin extremely slow. All i can think of is sending the percentage heating of the most hot part (basically the part that is closest to exploding). thoughts @phardy ?

**Comment by bespezzano** [comment]
> I guess the main issue is that each part has its own values rather than the ship as a whole. I cant see away of sending all the parts temperature readings without making the plugin extremely slow. All i can think of is sending the percentage heating of the most hot part (basically the part that is closest to exploding). thoughts @phardy ?

Considering each part has a temp, then % of hottest part would be a way of doing it. Not sure how useful the feature would be, thought it would be cool to have access to different alarms (temp, Gs, resources, etc)

**Comment by zitron-git** [comment]
% overheat of hottest part is what I used in the KSPSeialIO plugin, it works great because typically all you really want to know is: how close is any part to exploding? After that part explodes it automatically tells you the next one closes to exploding!

You only need to send a single byte and only need a single LED/dial to display the information.

**Comment by PBechon** [comment]
This message has been implemented in the current develop branch.
